#!/usr/bin/env python3
"""Embed Templates/ into Swift source.

xscaffold is installed by copying one file. A resource bundle sitting next to
that file would be left behind, and SwiftPM's `Bundle.module` reacts to a
missing bundle with `fatalError` — a crash with an internal message rather than
anything a user could act on. Compiling the templates in removes the failure
mode entirely.

Templates/ stays the place templates are written and reviewed; this script
mirrors it into Sources/ScaffoldCore/Generated/EmbeddedTemplates.swift, which is
committed so that a plain `swift build` needs no extra step. CI regenerates and
fails if the result differs.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "Templates"
OUTPUT = ROOT / "Sources" / "ScaffoldCore" / "Generated" / "EmbeddedTemplates.swift"

HEADER = """// Generated by Scripts/embed-templates.py. Do not edit.
//
// Edit the files under Templates/ and run `make templates`.

/// Every file under `Templates/`, keyed by its path relative to that directory.
///
/// Compiled in rather than shipped alongside the binary: `xscaffold` is
/// installed by copying a single file, and a resource bundle would not come
/// with it.
enum EmbeddedTemplates {
    static let all: [String: String] = [
"""

FOOTER = """    ]
}
"""


def raw_literal(text: str) -> str:
    '''A Swift raw multi-line literal holding `text` exactly.

    The delimiter grows until neither of the two sequences that mean something
    inside a raw literal can appear in the content:

    - three quote marks followed by the hashes would close the literal early.
    - a backslash followed by the hashes is an escape, so `\\#n` would silently
      become a newline and `\\#(x)` would try to interpolate. That one corrupts
      content rather than breaking the build, which is worse.
    '''
    hashes = "#"
    while '"""' + hashes in text or "\\" + hashes in text:
        hashes += "#"
    # Swift drops the newline before the closing delimiter, so writing one here
    # reproduces the file's own trailing newline when it has one.
    return f'{hashes}"""\n{text}\n"""{hashes}'


def collect() -> list[tuple[str, str]]:
    files = []
    for path in sorted(TEMPLATES.rglob("*")):
        if not path.is_file() or path.name == ".DS_Store":
            continue
        relative = path.relative_to(TEMPLATES).as_posix()
        try:
            files.append((relative, path.read_text(encoding="utf-8")))
        except UnicodeDecodeError:
            # An app icon would be the obvious candidate. Supporting binary
            # templates means base64 and a second code path; failing clearly
            # beats a decoding traceback from a build step.
            raise SystemExit(
                f"error: {relative} is not UTF-8 text. Binary templates are not supported."
            ) from None
    return files


def swift_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(files: list[tuple[str, str]]) -> str:
    body = "".join(
        f"        {swift_string(name)}: {raw_literal(contents)},\n"
        for name, contents in files
    )
    return HEADER + body + FOOTER


def main() -> int:
    files = collect()
    if not files:
        print("error: no templates found under Templates/", file=sys.stderr)
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(files), encoding="utf-8")
    print(f"embedded {len(files)} templates into {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
