included:
  - App
  - Tests

excluded:
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 2

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
